### ISSUE TITLE
Add Citation File

### ISSUE THREAD

**Issue by P-S-S-M** [ukaea/bom_analysis#19]
**Is your feature request related to a problem? Please describe.**
The problem is that it is not easy to reference git repos

**Describe the solution you'd like**
Add a citation file format: https://citation-file-format.github.io/

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by cmacmackin** [comment]
Another useful thing to do to aid citations is use [Zenodo](https://zenodo.org/). This is a service operated by CERN which will archive releases of your code (I think it can be used for other digital data too). It also issues you with DOIs, allowing papers to cite not only your code but the exact version.
