### ISSUE TITLE
Adopt GitHub Actions for CI

### ISSUE THREAD

**Issue by cmacmackin** [ukaea/bom_analysis#2]
This contains the configuration file for GitLab CI but obviously that won't work now you're on GitHub. Instead use [GitHub Actions](https://docs.github.com/en/actions). These have some very powerful features, allowing you to reuse other people's configurations across repositories. For an example of their use in a Python code, see the [InDiCA project](https://github.com/ukaea/Indica/blob/master/.github/workflows/tests.yml).

**Comment by P-S-S-M** [comment]
All gitlab workflows running, including the deployment to PyPI. Should be good to close issue
