### ISSUE TITLE
Deploy documentation to ReadTheDocs

### ISSUE THREAD

**Issue by cmacmackin** [ukaea/bom_analysis#3]
[ReadTheDocs](https://readthedocs.org/) is a free service for hosting documentation for your software. It builds the documentation with Sphinx and is fairly straight-forward to configure (see the [tutorial](https://docs.readthedocs.io/en/stable/tutorial/)). The project will have to be made open source before you can use it.

**Comment by P-S-S-M** [comment]
- [ ] Change doc link in readme
- [ ] Change example link in docs and readme
- [ ] Get readthedocs to build documentation from text in docstrings/remove text from docstrings and store in .rst files
