### ISSUE TITLE
Set up SonarCloud integration

### ISSUE THREAD

**Issue by cmacmackin** [ukaea/bom_analysis#4]
On GitLab, the CI made use of a private UKAEA instance of SonarQube. This will no longer be available, now that the code is hosted on GitHub. Instead it should use [SonarCloud](https://sonarcloud.io/), the SaaS version of SonarQube. The project will need to be made open source before it can be registered with SonarCloud for free.

**Comment by cmacmackin** [comment]
I've done that now (I think).

**Comment by P-S-S-M** [comment]
Yeah all working now, issue should be able to be closed
