### ISSUE TITLE
Create PyPI releases

### ISSUE THREAD

**Issue by cmacmackin** [ukaea/bom_analysis#5]
This package should be published to the [Python Package Index](https://pypi.org/) (PyPI) so that it can be pip-installed by others. The process of building the package and, if it is a release, deploying it to PyPI should be automated using GitHub Actions.

**Comment by P-S-S-M** [comment]
Release on PyPI complete and automated via github actions

**Comment by P-S-S-M** [comment]
Issue should be able to be closed.

**Comment by cmacmackin** [comment]
Might want to add a badge for it at the top of your readme. E.g.
```
[![Latest Release](https://img.shields.io/pypi/v/bom_analysis)](https://pypi.org/project/bom-analysis/)
```

[![Latest Release](https://img.shields.io/pypi/v/bom_analysis)](https://pypi.org/project/bom-analysis/)
